### ISSUE TITLE
Wysiwyg plugin makes git changes display useless

### ISSUE THREAD

**Issue by TadeasPilar** [adamerose/vscode-markdown-wysiwyg#18] opened 2024-06-13 13:18 UTC
Wysiwyg plugin completely takes over .md file editing. Can this be disabled?
I would like to open all markdowns in raw text and only change to wysiwyg when I want to.

The most annoying downside of always wysiwyg editing is the git diff display. For any other text file, changes are displayed in red and green. When wysiwyg opens, the changes are still there, but the color is gone. This makes the changes very hard to spot, which is really not the point of such split window display.

![image](https://github.com/adamerose/vscode-markdown-wysiwyg/assets/69154224/2dc578f1-c22e-490d-98be-eec14f104bea)

**Comment by adamerose** [comment] 2024-06-20 14:24
Duplicate of #16 

Solution is to change the default editor back to plaintext. I'm not aware of any way to have my WYSIWYG as the default editor when directly opening `.md` files but not when opening them in a Git diff or File Compare context.

**Closed as completed by adamerose** 2024-06-20 14:24 UTC

**Comment by TadeasPilar** [comment] 2024-06-21 09:51
Ok, how do I do that? I am fine with plaintext as default everywhere. I was unable how change default editor.

**Comment by adamerose** [comment] 2024-06-30 20:56
Right click a .md file, Open With, bottom option:
![image](https://github.com/adamerose/vscode-markdown-wysiwyg/assets/10884874/1fc96bfa-5942-40ef-b2fe-bbc39533d672)
